/*
 * SPDX-FileCopyrightText: 2024-2025 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */
#pragma once

// *INDENT-OFF*

#include "drivers/esp_panel_drivers_conf_internal.h"

#ifndef ESP_PANEL_DRIVERS_INCLUDE_INSIDE

/*
 * Define the driver configuration - EK79007 only
 */
#ifndef ESP_PANEL_DRIVERS_LCD_USE_EK79007
#ifdef CONFIG_ESP_PANEL_DRIVERS_LCD_USE_EK79007
#define ESP_PANEL_DRIVERS_LCD_USE_EK79007 CONFIG_ESP_PANEL_DRIVERS_LCD_USE_EK79007
#else
#define ESP_PANEL_DRIVERS_LCD_USE_EK79007 (1)  // ✅ Activé par défaut
#endif
#endif

#ifndef ESP_PANEL_DRIVERS_LCD_COMPILE_UNUSED_DRIVERS
#ifdef CONFIG_ESP_PANEL_DRIVERS_LCD_COMPILE_UNUSED_DRIVERS
#define ESP_PANEL_DRIVERS_LCD_COMPILE_UNUSED_DRIVERS CONFIG_ESP_PANEL_DRIVERS_LCD_COMPILE_UNUSED_DRIVERS
#else
#define ESP_PANEL_DRIVERS_LCD_COMPILE_UNUSED_DRIVERS (0)
#endif
#endif

#endif // ESP_PANEL_DRIVERS_INCLUDE_INSIDE

/*
 * Enable EK79007 driver
 */
#ifndef ESP_PANEL_DRIVERS_LCD_ENABLE_EK79007
#if ESP_PANEL_DRIVERS_LCD_COMPILE_UNUSED_DRIVERS || ESP_PANEL_DRIVERS_LCD_USE_EK79007
#define ESP_PANEL_DRIVERS_LCD_ENABLE_EK79007  (1)
#else
#define ESP_PANEL_DRIVERS_LCD_ENABLE_EK79007  (0)
#endif
#endif

// *INDENT-ON*
