/*
 * SPDX-FileCopyrightText: 2023-2025 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */
#pragma once

// *INDENT-OFF*

#include "drivers/esp_panel_drivers_conf_internal.h"

#ifndef ESP_PANEL_DRIVERS_INCLUDE_INSIDE

/*
 * Define the driver configuration - PWM_LEDC only
 */
#ifndef ESP_PANEL_DRIVERS_BACKLIGHT_USE_PWM_LEDC
#ifdef CONFIG_ESP_PANEL_DRIVERS_BACKLIGHT_USE_PWM_LEDC
#define ESP_PANEL_DRIVERS_BACKLIGHT_USE_PWM_LEDC CONFIG_ESP_PANEL_DRIVERS_BACKLIGHT_USE_PWM_LEDC
#else
#define ESP_PANEL_DRIVERS_BACKLIGHT_USE_PWM_LEDC (1)  // ✅ Activé par défaut
#endif
#endif

#ifndef ESP_PANEL_DRIVERS_BACKLIGHT_COMPILE_UNUSED_DRIVERS
#ifdef CONFIG_ESP_PANEL_DRIVERS_BACKLIGHT_COMPILE_UNUSED_DRIVERS
#define ESP_PANEL_DRIVERS_BACKLIGHT_COMPILE_UNUSED_DRIVERS CONFIG_ESP_PANEL_DRIVERS_BACKLIGHT_COMPILE_UNUSED_DRIVERS
#else
#define ESP_PANEL_DRIVERS_BACKLIGHT_COMPILE_UNUSED_DRIVERS (0)
#endif
#endif

#endif // ESP_PANEL_DRIVERS_INCLUDE_INSIDE

/*
 * Enable PWM_LEDC driver
 */
#ifndef ESP_PANEL_DRIVERS_BACKLIGHT_ENABLE_PWM_LEDC
#if ESP_PANEL_DRIVERS_BACKLIGHT_COMPILE_UNUSED_DRIVERS || ESP_PANEL_DRIVERS_BACKLIGHT_USE_PWM_LEDC
#define ESP_PANEL_DRIVERS_BACKLIGHT_ENABLE_PWM_LEDC  (1)
#else
#define ESP_PANEL_DRIVERS_BACKLIGHT_ENABLE_PWM_LEDC  (0)
#endif
#endif

// *INDENT-ON*
