/*
 * SPDX-FileCopyrightText: 2024-2025 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */
#pragma once

#include "drivers/esp_panel_drivers_conf_internal.h"

// *INDENT-OFF*

#ifndef ESP_PANEL_DRIVERS_INCLUDE_INSIDE

/*
 * Define the driver configuration - MIPI DSI only
 */
#if SOC_MIPI_DSI_SUPPORTED
#ifndef ESP_PANEL_DRIVERS_BUS_USE_MIPI_DSI
#ifdef CONFIG_ESP_PANEL_DRIVERS_BUS_USE_MIPI_DSI
#define ESP_PANEL_DRIVERS_BUS_USE_MIPI_DSI CONFIG_ESP_PANEL_DRIVERS_BUS_USE_MIPI_DSI
#else
#define ESP_PANEL_DRIVERS_BUS_USE_MIPI_DSI (1)  // ✅ Activé par défaut
#endif
#endif
#else
#undef ESP_PANEL_DRIVERS_BUS_USE_MIPI_DSI
#define ESP_PANEL_DRIVERS_BUS_USE_MIPI_DSI (0)
#endif

#ifndef ESP_PANEL_DRIVERS_BUS_COMPILE_UNUSED_DRIVERS
#ifdef CONFIG_ESP_PANEL_DRIVERS_BUS_COMPILE_UNUSED_DRIVERS
#define ESP_PANEL_DRIVERS_BUS_COMPILE_UNUSED_DRIVERS CONFIG_ESP_PANEL_DRIVERS_BUS_COMPILE_UNUSED_DRIVERS
#else
#define ESP_PANEL_DRIVERS_BUS_COMPILE_UNUSED_DRIVERS (0)
#endif
#endif

#endif // ESP_PANEL_DRIVERS_INCLUDE_INSIDE

/*
 * Enable MIPI DSI driver
 */
#if SOC_MIPI_DSI_SUPPORTED
#ifndef ESP_PANEL_DRIVERS_BUS_ENABLE_MIPI_DSI
#if ESP_PANEL_DRIVERS_BUS_COMPILE_UNUSED_DRIVERS || ESP_PANEL_DRIVERS_BUS_USE_MIPI_DSI
#define ESP_PANEL_DRIVERS_BUS_ENABLE_MIPI_DSI  (1)
#else
#define ESP_PANEL_DRIVERS_BUS_ENABLE_MIPI_DSI  (0)
#endif
#endif
#else
#undef ESP_PANEL_DRIVERS_BUS_ENABLE_MIPI_DSI
#define ESP_PANEL_DRIVERS_BUS_ENABLE_MIPI_DSI  (0)
#undef ESP_PANEL_DRIVERS_BUS_USE_MIPI_DSI
#define ESP_PANEL_DRIVERS_BUS_USE_MIPI_DSI  (0)
#endif

// *INDENT-ON*
